# ===========================================Welcome To CoMET===========================================
# This is where most all functionality of CoMET can be specified. You can change any of the supplied 
# variables OR you can use a default suite of paramateres setup for different model and observation
# input types. 


# SETUP VARIABLES: These determine input data types and locations
verbose: True # Whether to use verbose output
parallel_processing: True # [bool] Whether or not to use parallel processing for certain tasks
max_cores: 32 # Number of cores to use if parallel_processing==True; Enter None for unlimited

model_type: "" # Current Options: ['WRF', 'RAMS']
path_to_model: "" # Path to the model outputs (should use *, like "/home/wrfout/wrfout_d02_*")

observation_type: "" # Current Options: ['NEXRAD', 'GOES-Satellite']
path_to_observation: "" # Path to the observation outputs (should use *, like "/home/wrfout/wrfout_d02_*")


# TRACKING VARIABLES: These determine values for your tracker of choice
model_tracker: "" # Current Options: ['tobac']
model_tracking_type: "" # Current Options: ['IC', 'MCS', 'CP'] for Isolated convection, meso-scale convective systems, and cold pools, respectively
model_tracking_variable: "" # Current Options: ['DBZ', 'TB', 'W'] for Radar reflectivity, brightness temperature, and updraft velocity, respectively
model_tracking_suite: "" # Default set of parameters for various trackers. Current Options: ['none', 't_wrf', 't_rams']

observation_tracker:  "" # Current Options: ['tobac']
observation_tracking_type: "" # Current Options: ['IC', 'MCS', 'CP'] for Isolated convection, meso-scale convective systems, and cold pools, respectively
observation_resolution: "" # Resolution of your input observations in meters
observation_tracking_suite: "" # Default set of parameters for various trackers. Current Options: ['none', 't_nexrad', 't_goes']


# SPECIFIC TRACKER PARAMETERS: Only fill out for your selected tracker
# TOBAC PAAMETERS:
tobac:
    feature_id:
        threshold: [3,5,10]
        target: 'maximum'
        position_threshold: 'weighted_diff'
        sigma_threshold: 0.5
        n_min_threshold: 4
    
    linking: 
        method_linking: 'predict'
        adaptive_stop: 0.2
        adaptive_step: 0.95
        order: 1
        subnetwork_size: 10
        memory: 1
        v_max: 20
    
    segmentation:
        method: 'watershed'
        threshold: 3
    

# OBSERVATION PARAMETERS: Only fill out for your selected observation type

# NEXRAD
nexrad:
    bounds: [-100, -95.5, 35.5, 38.5] # In form [lon_min,lon_max,lat_min,lat_max]

    gridding: # only if gridding is needed 
        # gridding_algo: 'map_gates_to_grid'
        grid_shape: (40, 401, 401)
        grid_limits: ((500, 20000), (-200000., 200000.), (-200000., 200000.))
        # h_factor: 0.
        # nb: 0.6
        # bsp: 1.
        # min_radius: 200.
    
    
# GOES
goes:
    bounds: [-100, -95.5, 35.5, 38.5] # In form [lon_min,lon_max,lat_min,lat_max]
    
    
# ANALYSIS PARAMETERS: Select which variables you would like to calculate or which suite of variables. 
analysis_variables:
    eth_15: True
    eth_30: True