# SETUP VARIABLES: These determine basic CoMET functionality
verbose: True # Whether to use verbose output
parallel_processing: True # [bool] Whether or not to use parallel processing for certain tasks
max_cores: 32 # Number of cores to use if parallel_processing==True; Enter None for unlimited

# Structered in this form:
# Observation Type:
#   path_to_data
#   additional_observation_parameters
#
#   tracker:
#       tracker_params
#
#       analysis:
#           analysis_variables

# WRF
wrf:
    path_to_data: "/D3/data/thahn/wrf/wrfout_2023_07_09/wrfout_d02*"

    feature_tracking_var: "dbz" #DBZ, TB, WA
    segmentation_var: "dbz"
            
    moaap:
        tracking_save_path: "/D3/data/thahn/wrf/wrfout_2023_07_09/moaap_test/"
        MinTimePR: 0.5
        MinAreaPR: 10
        
        analysis:
            # None yet