# ===========================================Welcome To CoMET===========================================
# This is where most all functionality of CoMET can be specified. You can change any of the supplied 
# variables OR you can use a default suite of paramateres setup for different model and observation
# input types. 


# SETUP VARIABLES: These determine basic 
verbose: True # Whether to use verbose output
parallel_processing: True # [bool] Whether or not to use parallel processing for certain tasks
max_cores: 32 # Number of cores to use if parallel_processing==True; Enter None for unlimited

# Structered in this form:
# Observation Type:
#   path_to_data
#   additional_observation_parameters
# 
#   tracker:
#       tracker_params
#
#   analysis:
#       analysis_variables
wrf:
    path_to_data: '/D3/data/thahn/wrf/wrfout_2023_07_09/wrfout_d02*'

    tracking_type: 'IC'

    feature_tracking_var: 'w'
    segmentation_var: 'w'

    tobac:
        feature_id:
            threshold: [3,5,10,15]
            target: 'maximum'
            position_threshold: 'weighted_diff'
            sigma_threshold: 0.5
            n_min_threshold: 4
            
        linking: 
            method_linking: 'predict'
            adaptive_stop: 0.2
            adaptive_step: 0.95
            order: 1
            subnetwork_size: 10
            memory: 1
            v_max: 20