#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 24 12:17:45 2024

@author: thahn
"""

# =============================================================================
# This defines the primary functionality of the analysis module for CoMET. Including the primary get_var function which works similar to wrf-python's getvar
# =============================================================================


"""
Inputs:
    variable: Which variable to calculate. See list below.
    analysis_object: The output of CoMET_start and/or an object generated by create_analysis_object
Outputs:
    Maybe????var_xarray: An xarray DataArray/(Dataset?) containing the variable of interest



Valid Variables:
    "ETH"




"""
def get_var(variable, analysis_object):
    print('hiiiii :333')