name: website

# build the documentation whenever there are new commits on master or testing
on:
  push:
    branches: [ "master", "testing" ]
  pull_request:
    branches: [ "master", "testing" ]

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install all dependencies (including pdoc)
      - run: pip install -e .
      - run: pip install -e pdoc 
      # Build your documentation into docs/.
      - run: python -m pdoc CoMET --logo "https://raw.githubusercontent.com/ASCENT-BNL/CoMET/master/docs/images/comet_logo.png" -o ./docs

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4