# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Linting

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-version: latest
          miniforge-variant: mambaforge
          channel-priority: strict
          channels: conda-forge
          show-channel-urls: true
          use-only-tar-bz2: true
          
    - name: Install dependencies
      run: |
          mamba install --yes pylint
          pip install .
    - name: Run pylint
        run: |
          pylint CoMET --disable=C --exit-zero
        id: main_score
