name: comet_run_tests

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This job installs dependencies and runs tests across a matrix of python and OS versions.

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    if: github.repository == 'travis-j-hahn/CoMET'
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [macos, ubuntu, windows]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Install micromamba and dependencies
      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          activate-environment: CoMET-dev
          cache-downloads: true
          channels: conda-forge
          channel-priority: strict
          python-version: ${{ matrix.python-version }}

      - name: Fetch all history for all tags and branches
        run: |
           git fetch --prune --unshallow

      - name: Install CoMET
        shell: bash -l {0}
        run: |
          mamba install --yes pytest
          python -m pip install -e . --no-deps --force-reinstall

      - name: Run Tests
        id: run_tests
        shell: bash -l {0}
        run: |
          python -m pytest -v 
